# .github/workflows/percy.yml

# Workflow name
name: 'Percy'

# Event for the workflow
on:
  pull_request:
    types: [ labeled, closed ]
  push:
    branches:
      - master

# closed not working since we want master to trigger the build
# contains(github.event.pull_request.labels.*.name, 'percy')

# List of jobs
jobs:
  build:
    # if: ${{ github.event.label.name == 'percy' }}
    if: contains(github.event.pull_request.labels.*.name, 'percy')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        run: npm run percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
